### PR TITLE
Major overhaul

### PR DESCRIPTION
**Pull request by jrochkind**

### CODE REVIEW

**Comment by tampakis** [comment]
@jrochkind Any way you can squash these into a single commit?

**Comment by jrochkind** [comment]
I could definitely do that. Do you think it would be better?  I tried to mostly make the commits meaningful and well-organized already, so I would rather have them separate to show the history and provide the commit messages with reasoning behind each change (which show up in git blame for instance).  

But if you'd rather have em squashed, I can squash em!

**Comment by jpstroop** [comment]
This is a small enough repo, and since this basically constitutes a rewrite, it probably isn't a bad idea to keep all of this history. :+1: to merging as-is.

**Comment by jrochkind** [comment]
Yeah, as I think about it more...

The point of rewriting history is to provide a more clear narrative of what changes were actually made when someone is reviewing the commit history with git log or git blame. Or to give good individual commits someone can revert if they think it introduced a bug or whatever. 

I think my existing commit history, in which I tried to take care to make good commits with good messages (it's not perfect, but I tried) is a pretty good narrative. I think one giant commit with the commit message "Giant commit that majorly overhauls everything" does not provide any value added. That's the kind of commit that's considered a bad practice, actually, right?

That's my case for merging as is vs squashing to one mega commit!

Once we do merge, I'd like us to do a release to rubygems? Not sure if we should call it 1.0, or be more cautious and call it 0.9?  

@tampakis, you want to do the release so you learn how to do it, and get registered as the owner of the gem on rubygems (you can then add me or any other collaborators like jon as co-owners too).  After this merge, the bundler-provided rake tasks are included, so after checking you have the version you want in the version.rb file, you can release with a simple `rake release`.

**Comment by tampakis** [comment]
Sure this sounds good. I’ll merge and release on Wednesday when I’m back in the office. I like the sound of 1.0

**Comment by jpstroop** [comment]
I think you should go with 0.9.0 or something like that until you've tried to plug this into our indexer as well; you never know what tweaks might surface (which _could_ include breaking changes and thus immediately force you to 2.0.0) from the experience of testing on another system. You could cut 1.0.0 the very next day if all goes smoothly.

**Comment by jrochkind** [comment]
Awesome thanks. 

Can we release to rubygems now? Note before releasing you'll want to update `./lib/lcsort/version.rb` to be the version number you want to release, and commit that. 

You should then be able to release with `rake release`.  But can you add me and maybe Jon as gem owners too, so we can release in the future? (It'll make you the sole owner on first release, then you can add us, if you know the email addresses we have registered with rubygems. Mine is jonathan at dnil.net.

http://guides.rubygems.org/command-reference/#gem-owner

**Comment by tampakis** [comment]
Yes that's what I'm working on.

**Pull request merged**
